### ISSUE TITLE
Fix Git LFS path in Dockerfile

### ISSUE THREAD

**Issue by mikkokotila** [Lotus-King-Research/Padma-Backend#74]
`index.sqlite` path has to be updated.

**Comment by rishvantsingh** [comment]
Ill do it.

**Comment by mikkokotila** [comment]
## what should be changed to what

`RUN wget https://github.com/Lotus-King-Research/Padma-Backend/raw/api-v2/app/data/index.sqlite`

It still works, but it should be changed to: 

`RUN wget https://github.com/Lotus-King-Research/Padma-Backend/raw/master/app/data/index.sqlite`
